# --- Font Configuration ---
font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

# --- Ligature Settings ---
# Cascadia Code supports ligatures (e.g., != becoming ≠). 
# Set this to 'always' to enable them or 'never' to disable.
disable_ligatures yes
enable_audio_bell no 
shell zsh 

shell_integration disable

cursor_shape block
url_color #61afef
url_style curly 

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 20
window_padding_height 25

background_opacity 0.8
scrollbar_handle_opacity 0  
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

confirm_os_window_close 0



#colors below this line
background            #282f32
foreground            #dad9df
cursor                #d35f5a
selection_background  #eeb7ab
color0                #282f32
color8                #092027
color1                #ca1d2c
color9                #d35f5a
color2                #edb7ab
color10               #d35f5a
color3                #b7aa9a
color11               #a86571
color4                #2e78c1
color12               #7c84c4
color5                #c0226e
color13               #5b5db2
color6                #309185
color14               #81908f
color7                #e9e2cd
color15               #fcf4de
selection_foreground #282f32

